stages:
  - build
  - test
  - danger

before_script: 
  - bundle install danger

build_project:
  stage: build
  script:
    - xcodebuild clean -project iOS-Boilerplate.xcodeproj -scheme iOS-Boilerplate | xcpretty
  tags:
    - xcode

fastlane_test:
  stage: test
  script:
    - bundle update
    - bundle exec fastlane tests
  tags:
    - xcode

danger:
  stage: danger
  script:
    - bundle exec danger

variables:
  GIT_SSL_NO_VERIFY: "1"
