stages:
  - build
  - lint

before_script: 
  - bundle install

build_project:
  stage: build
  script:
    - bundle exec fastlane tests
    - bundle exec fastlane cov
    - bundle exec fastlane post_cov_to_gitlab
  tags:
    - xcode

lint_project:
  stage: lint
  script:
    - bundle exec fastlane lint
    - bundle exec fastlane post_swiftlint_to_gitlab
  tags:
    - xcode

variables:
  GIT_SSL_NO_VERIFY: "1"
  GIT_SUBMODULE_STRATEGY: recursive
