stages:
  # - build
  - lint

before_script: 
  - bundle install

# build_project:
#   stage: build
#   script:
#     - xcodebuild clean build test -project iOS-Boilerplate.xcodeproj -scheme iOS-Boilerplate | xcpretty
#     - xcov -p iOS-Boilerplate.xcodeproj -s iOS-Boilerplate -o xcov_output
#     - 'CI_MERGE_REQUEST_ID=$(curl --request GET --header "Private-Token: $GITLAB_PERSONAL_API_PRIVATE_TOKEN" "https://gitlab.veladan.org/api/v4/projects/$CI_PROJECT_ID/repository/commits/$CI_COMMIT_SHA/merge_requests" --insecure | jq --raw-output ".[0].iid")'
#     - 'curl --request POST --header "Private-Token: $GITLAB_PERSONAL_API_PRIVATE_TOKEN" -d @xcov_output/report.md https://gitlab.veladan.org/api/v4/projects/$CI_PROJECT_ID/merge_requests/$CI_MERGE_REQUEST_ID/notes --insecure'
#   tags:
#     - xcode

lint_project:
  stage: lint
  script:
    - echo "body=" > report.html
    - swiftlint lint --quiet --enable-all-rules --reporter html >> report.html
    - 'CI_MERGE_REQUEST_IID=$(curl --request GET --header "Private-Token: $GITLAB_PERSONAL_API_PRIVATE_TOKEN" "https://gitlab.veladan.org/api/v4/projects/$CI_PROJECT_ID/repository/commits/$CI_COMMIT_SHA/merge_requests" --insecure | jq --raw-output ".[0].iid")'
    - '[ -n CI_MERGE_REQUEST_IID ] &&curl --request POST --header "Private-Token: $GITLAB_PERSONAL_API_PRIVATE_TOKEN" -d @report.html https://gitlab.veladan.org/api/v4/projects/$CI_PROJECT_ID/merge_requests/$CI_MERGE_REQUEST_IID/notes --insecure'
  tags:
    - xcode

variables:
  GIT_SSL_NO_VERIFY: "1"
  GIT_SUBMODULE_STRATEGY: recursive
