name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"

jobs:
  cocoapods:
    name: CocoaPods Lint
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: bundle install
      - run: ./test podspec

  xcode:
    name: Xcode ${{ matrix.xcode }} - ${{ matrix.platform }}
    runs-on: macos-latest
    strategy:
      matrix:
        xcode: [11.7, 12.4]
        platform: [macos, ios, tvos]
      fail-fast: false
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app
    steps:
      - uses: actions/checkout@v2
      - run: ./test ${{ matrix.platform }}
      - run: ./test ${{ matrix.platform }}_xcodespm

  swiftpm_darwin:
    name: SwiftPM, Darwin, Xcode ${{ matrix.xcode }}
    runs-on: macos-latest
    strategy:
      matrix:
        xcode: [11.7, 12.4]
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app
    steps:
      - uses: actions/checkout@v2
      - run: ./test swiftpm

  swiftpm_linux:
    name: SwiftPM, Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container:
          - swift:5.2
          - swift:5.3
          - swift:5.4
          - swiftlang/swift:nightly
      fail-fast: false
    container: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v2
      - run: swift build -Xswiftc -suppress-warnings
      - run: swift test -Xswiftc -suppress-warnings --enable-test-discovery
