included:
  - Sources
  - Tests

excluded:
  - Package.swift
  - Carthage/Checkouts
  - Tests/NimbleTests/XCTestManifests.swift
  - Tests/NimbleTests/Helpers/XCTestCaseProvider.swift

disabled_rules:
  - 

opt_in_rules:
  - yoda_condition

identifier_name:
  max_length: 50
  excluded:
    - x
    - l
    - r
    - e
    - n1
    - n2
    - to
  allowed_symbols:
      - _

line_length:
  warning: 160
  error: 240
  ignores_comments: true
  ignores_function_declarations: true

trailing_comma:
  mandatory_comma: true
