branches:
  only:
    - master
    - 8.x-branch

language: generic
matrix:
  include:
    - &cocoapods
      name: CocoaPods Lint
      os: osx
      osx_image: xcode10.3
      install: bundle install
      script: ./test podspec
    - &xcode
      name: Xcode 10.1 / Swift 4.2
      os: osx
      osx_image: xcode10.1
      script:
        - ./test macos
        - ./test ios
        - ./test tvos
    - <<: *xcode
      name: Xcode 10.3 / Swift 5.0
      osx_image: xcode10.3
    - &swiftpm_darwin
      name: SwiftPM / Darwin / Swift 4.2
      os: osx
      osx_image: xcode10.1
      script: ./test swiftpm
    - <<: *swiftpm_darwin
      name: SwiftPM / Darwin / Swift 5.0
      osx_image: xcode10.3
    - &swiftpm_linux
      name: SwiftPM / Linux / Swift 4.2.4
      os: linux
      dist: trusty
      sudo: required
      env:
        - SWIFT_VERSION=4.2.4
      install:
        - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
      script:
        - ./test swiftpm
    - <<: *swiftpm_linux
      name: SwiftPM / Linux / Swift 5.0.3
      env:
        - SWIFT_VERSION=5.0.3
    - <<: *swiftpm_linux
      name: SwiftPM / Linux / Swift 5.1 Development
      env:
        - SWIFT_VERSION=5.1-DEVELOPMENT-SNAPSHOT-2019-09-05-a
install: true
script:
  - ./test $TYPE

notifications:
  email: false
