# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    get_certificates           # invokes cert
    get_provisioning_profile   # invokes sigh
    build_app(scheme: "iOS-Boilerplate")
    upload_to_testflight
  end

  lane :build do
    get_certificates           # invokes cert
    get_provisioning_profile   # invokes sigh
    build_app(scheme: "iOS-Boilerplate")
  end

  lane :tests do
    run_tests(scheme: "iOS-Boilerplate")
  end

  lane :cov do
    xcov(
      scheme: "iOS-Boilerplate",
      markdown_report: true,
      output_directory: "xcov_output"
    )
  end

  lane :lint do
    swiftlint(
    mode: :lint,
    output_file: "swiftlint.result",
    quiet: true,
    reporter: "html",
    ignore_exit_status: true
  )
  end

  def setMergeId
    `CI_MERGE_REQUEST_IID=$(curl --request GET --header "Private-Token: $GITLAB_PERSONAL_API_PRIVATE_TOKEN" "https://gitlab.veladan.org/api/v4/projects/$CI_PROJECT_ID/repository/commits/$CI_COMMIT_SHA/merge_requests" --insecure | jq --raw-output ".[0].iid")`
    `echo CI_MERGE_REQUEST_IID`
    `echo $CI_MERGE_REQUEST_IID`
    `echo CI_MERGE_REQUEST_IID`
  end

  lane :post_swiftlint_to_gitlab do
    setMergeId()
    `echo "body=" > ../report.html`
    `cat ../swiftlint.result >> ../report.html`
    `[ -n CI_MERGE_REQUEST_IID ] && curl --request POST --header "Private-Token: $GITLAB_PERSONAL_API_PRIVATE_TOKEN" -d @../report.html https://gitlab.veladan.org/api/v4/projects/$CI_PROJECT_ID/merge_requests/$CI_MERGE_REQUEST_IID/notes --insecure`
  end

  lane :post_cov_to_gitlab do
    setMergeId()
    `echo "body=" > ../xreport.md`
    `cat ../xcov_output/report.md >> ../xreport.md`
    `'[ -n CI_MERGE_REQUEST_IID ] && curl --request POST --header "Private-Token: $GITLAB_PERSONAL_API_PRIVATE_TOKEN" -d @../xreport.md https://gitlab.veladan.org/api/v4/projects/$CI_PROJECT_ID/merge_requests/$CI_MERGE_REQUEST_IID/notes --insecure`
    `echo "curl --request POST --header "Private-Token: $GITLAB_PERSONAL_API_PRIVATE_TOKEN" -d @../xreport.md https://gitlab.veladan.org/api/v4/projects/$CI_PROJECT_ID/merge_requests/$CI_MERGE_REQUEST_IID/notes --insecure"`
  end
end
