# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    get_certificates           # invokes cert
    get_provisioning_profile   # invokes sigh
    carthage
    build_app(scheme: "iOS-Boilerplate")
    upload_to_testflight
  end

  lane :build do
    get_certificates           # invokes cert
    get_provisioning_profile   # invokes sigh
    carthage
    build_app(scheme: "iOS-Boilerplate")
  end

  lane :tests do
    run_tests(scheme: "iOS-Boilerplate")
  end

  lane :cov do
    xcov(
      scheme: "iOS-Boilerplate",
      markdown_report: true,
      output_directory: "xcov_output"
    )
  end

  lane :lint do
    swiftlint(
    mode: :lint,
    output_file: "swiftlint.result",
    quiet: true,
    reporter: "html",
    ignore_exit_status: true
  )
  end
end
