language: objective-c
xcode_workspace: FLEX.xcworkspace
matrix:
    include:
        - xcode_scheme: UICatalog
          xcode_sdk: iphonesimulator
        - xcode_scheme: FLEX
          xcode_sdk: iphonesimulator
