//
//  LoginWorker.swift
//  iOS-Boilerplate
//
//  Created by Daniel Vela Angulo on 11/01/2019.
//  Copyright (c) 2019 veladan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class LoginWorker {
    func validate(userName str: String?) -> Bool {
        guard let str = str,
                  str.isEmpty == false else {
            return false
        }
        return true
    }

    func validate(password str: String?) -> Bool {
        guard let str = str,
                  str.isEmpty == false else {
            return false
        }
        return true
    }

    func doSignIn(for userName: String,
                  and password: String,
                  onFinish: @escaping (Login.Process.Response.Result) -> Void) {
        DispatchQueue.global(qos: .userInteractive).async {
            Thread.sleep(forTimeInterval: 4.0)
            DispatchQueue.main.async {
                if userName == "dani" && password == "1234" {
                    onFinish(.loginOk)
                } else {
                    onFinish(.loginInvalid)
                }
            }
        }
    }
}
